#!/bin/bash

# Forked by benkulbertis/cloudflare-update-record.sh
# CHANGE THESE
api_token="YQSn-xWAQiiEh9qM58wZNnyQS7FUdoqGIUAbrh7T" # Create a token with edit Zone DNS permission on https://dash.cloudflare.com/profile/api-tokens
zone_identifier="f1nd7h3fuck1n6z0n31d3n71f13r4l50"   # Can be found in the "Overview" tab of your domain
record_name="ipv4.example.org"                       # Which record you want to be synced

# DO NOT CHANGE LINES BELOW
ip=$(curl -s https://ipv4.icanhazip.com/)

# SCRIPT START
printf '[Cloudflare DDNS] Check Initiated\n'

# Seek for the record
record=$(curl -s -X GET "https://api.cloudflare.com/client/v4/zones/$zone_identifier/dns_records?name=$record_name" -H "Authorization: Bearer $api_token" -H "Content-Type: application/json")

# Can't do anything without the record
if printf '%s' "$record" | grep -q '"count":0'; then
  >&2 printf '[Cloudflare DDNS] Record does not exist, perhaps create one first?\n'
  exit 1
fi

# Set existing IP address from the fetched record
old_ip=$(printf '%s' "$record" | grep -Po '(?<="content":")[^"]*' | head -1)

# Compare if they're the same
if [ $ip == $old_ip ]; then
  printf '[Cloudflare DDNS] IP has not changed.\n'
  exit 0
fi

# Set the record identifier from result
record_identifier=$(printf '%s' "$record" | grep -Po '(?<="id":")[^"]*' | head -1)

# The execution of update
update=$(curl -s -X PUT "https://api.cloudflare.com/client/v4/zones/$zone_identifier/dns_records/$record_identifier" -H "Authorization: Bearer $api_token" -H "Content-Type: application/json" --data "{\"id\":\"$zone_identifier\",\"type\":\"A\",\"proxied\":false,\"name\":\"$record_name\",\"content\":\"$ip\",\"ttl\":120}")

# The moment of truth
case "$update" in
*"\"success\":false"*)
  >&2 printf '[Cloudflare DDNS] Update failed for %s.\nResponse:\n%s\n' "$record_identifier" "$update"
  exit 1
  ;;
*)
  printf '[Cloudflare DDNS] IPv4 address %s has been synced to Cloudflare.\n' "$ip"
  ;;
esac
