#!/bin/bash

# Forked by benkulbertis/cloudflare-update-record.sh
# Create an API token with edit Zone DNS permission on https://dash.cloudflare.com/profile/api-tokens
# Zone ID can be found in the "Overview" tab of your domain
if [ -z "${CF_API_TOKEN_FILE}" ]; then
  >&2 printf 'Missing CF_API_TOKEN_FILE environment variable\n'
  exit 1
fi
if [ -z "${CF_ZONE_ID}" ]; then
  >&2 printf 'Missing CF_ZONE_ID environment variable\n'
  exit 1
fi
if [ $# -ne 1 ]; then
  >&2 printf 'Usage: %s <record_name>\n' "$0"
  exit 1
fi

api_token=$(cat ${CF_API_TOKEN_FILE})
zone_identifier=${CF_ZONE_ID}
record_name=$1; shift

# DO NOT CHANGE LINES BELOW
ip=$(curl -s https://ipv4.icanhazip.com/)

# SCRIPT START
printf '[Cloudflare DDNS] Check Initiated\n'

# Seek for the record
record=$(curl -s -X GET "https://api.cloudflare.com/client/v4/zones/$zone_identifier/dns_records?name=$record_name" -H "Authorization: Bearer $api_token" -H "Content-Type: application/json")

# Can't do anything without the record
if printf '%s' "$record" | grep -q '"count":0'; then
  >&2 printf '[Cloudflare DDNS] Record does not exist, perhaps create one first?\n'
  exit 1
fi

# Set existing IP address from the fetched record
old_ip=$(printf '%s' "$record" | grep -Po '(?<="content":")[^"]*' | head -1)

# Compare if they're the same
if [ $ip == $old_ip ]; then
  printf '[Cloudflare DDNS] IP has not changed.\n'
  exit 0
fi

# Set the record identifier from result
record_identifier=$(printf '%s' "$record" | grep -Po '(?<="id":")[^"]*' | head -1)

# The execution of update
update=$(curl -s -X PATCH "https://api.cloudflare.com/client/v4/zones/$zone_identifier/dns_records/$record_identifier" -H "Authorization: Bearer $api_token" -H "Content-Type: application/json" --data "{\"id\":\"$zone_identifier\",\"type\":\"A\",\"name\":\"$record_name\",\"content\":\"$ip\"}")

# The moment of truth
case "$update" in
*"\"success\":false"*)
  >&2 printf '[Cloudflare DDNS] Update failed for %s.\nResponse:\n%s\n' "$record_identifier" "$update"
  exit 1
  ;;
*)
  printf '[Cloudflare DDNS] IPv4 address %s has been synced to Cloudflare.\n' "$ip"
  ;;
esac
